//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockApp.UIL.Gestor_Comercio.Gestionar_producto
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public int ID_CATEGORIA { get; set; }
        public bool ESTADO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_BAJA { get; set; }
        public int? ID_MARCA { get; set; }
    }
}
